import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import Footer from '@/components/footer';
import TailwindIndicator from '@/components/tailwind-indicator';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto flex min-h-screen w-full flex-col">
          <Header />
          <div>{children}</div>
          <Footer />
        </div>
        <TailwindIndicator />
      </body>
    </html>
  );
}
